### ISSUE TITLE
Cannot read property 0 of undefined

### ISSUE THREAD

**Issue by old-df38257622** [scambier/markov-strings#10]
Hello! I've been having pretty good luck with this package after finding out what was up with the sentences. But recently, I noticed this happening -- when I start my program, it works just fine for a minute, but then it errors out:
```
/workspace/LettersBot/node_modules/markov-strings/dist/index.js:23
        if (lodash_1.isString(data[0])) {
                                  ^

TypeError: Cannot read property '0' of undefined
    at new Markov (/workspace/LettersBot/node_modules/markov-strings/dist/index.js:23:35)
    at Object.<anonymous> (/workspace/LettersBot/app.js:116:20)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```
Line 116 in my app.js is:
```
client.newmarkov = new Markov(client.mkvdata, {
    stateSize: 2
})
```
So I don't see how generating a new Markov would be the issue. client.mkvdata is an array of objects, formatted like `{"string":"<:iwanttodie:306099449787318272>","author":"411953926456475649"}`. It looks like the problematic line in markov-strings is here: 
```
if (lodash_1.isString(data[0])) {
            data = data.map(s => ({ string: s }));
        }
```
Is this a problem with Lodash? Is it a problem with my corpus, somehow -- meaning I'll have to completely reset?

**Comment by scambier** [comment]
Hello!

 > Line 116 in my app.js is:
```
client.newmarkov = new Markov(client.mkvdata, {
    stateSize: 2
})
```

What the error is saying is that your `client.mkvdata` is undefined.

**Comment by old-df38257622** [comment]
Huh. I was sure this wasn't the problem; someone had, at some point, removed the one-liner to define the markov data. Thanks for pointing it out and getting me to actually check it out!
