### ISSUE TITLE
Unexpected token export

### ISSUE THREAD

**Issue by Temetz** [scambier/markov-strings#13]
Steps:

 - Create new node project, `npm init`
 - Add lib: `npm i markov-strings`
 - create new file: `index.js`
 - Paste the example from readme, remove the `import Markov from 'markov-strings'`
 - run `node index.js`
 - See the error:

```
/home/code/tests/markov-test/node_modules/lodash-es/lodash.js:10
export { default as add } from './add.js';
^^^^^^

SyntaxError: Unexpected token 'export'
```

**Comment by scambier** [comment]
Fixed in 3.0.1, thank you.
