### ISSUE TITLE
45mb plaintext corpus is empty

### ISSUE THREAD

**Issue by old-df38257622** [scambier/markov-strings#16]
Hello! While trying to test out markov-strings for a project with a fairly large corpus, it simply tells me that my corpus is empty, despite having 45mb of only plain text. This is a bit confusing since [markovify](https://github.com/jsvine/markovify) seems to have no problem handling it. Here's how I'm trying to set it up:

```
> const Markov = require("markov-strings").default
> const fs = require("fs")
> const data = fs.readFileSync("corpus.txt", "utf8").split("\n")
> data
[
  'what do we do about them',
  'frog hole',
  'fix their name',
  '',
  'they shall become `enemy`',
  ... 1040273 more items
]
> const markov = new Markov(data, { stateSize: 2 })
> const options = {
... maxTries: 20,
... filter: result => {
... return result.string.split(" ").length >= 5
... }
... }
undefined
> markov.generate(options)
Uncaught:
Error: Corpus is empty. There is either no data, or the data is not sufficient to create markov chains.
    at Markov.generate (C:\Users\letters\Projects\markov-strings-testing\node_modules\markov-strings\dist\index.js:145:19)
```

**Comment by scambier** [comment]
Hello :)

The correct syntax is the following:

```ts
const markov = new Markov({stateSize: 2})

// .addData() can be called as many times as needed to add data
markov.addData(data)

const result = markov.generate(options)
```

**Comment by old-df38257622** [comment]
This gives me a different error, which was actually the reason I was trying to use the old syntax in the first place:
```
> data.forEach((line) => {
... markov.addData(line)
... })
Uncaught TypeError: rawData.map is not a function
    at Markov.addData (C:\Users\letters\Projects\markov-strings-testing\node_modules\markov-strings\dist\index.js:53:29)
    at REPL80:2:8
    at Array.forEach (<anonymous>)
```

**Comment by scambier** [comment]
`markov.addData()` takes an array as a parameter.

If possible, I recommend to use `import Markov from 'markov-strings'` instead of `const Markov = require('markov-strings').default`. I think `require().default` doesn't provide any typing hints, which are quite useful to avoid these errors.

**Comment by old-df38257622** [comment]
Ah, thanks. addData has been chugging away at `data` for well over 10 minutes now. Node consistently uses 20% of my CPU and fluctuates over 5 minutes between 1gb and 500mb of ram usage. I'm not sure if markov-strings is equipped to handle this amount of data, but maybe that's out of the scope of this issue?

**Comment by scambier** [comment]
I don't think I ever tried loading a million lines, so no idea how long it should take 🤷‍♂️
A user from a previous issue (#9) noted it was taking 7 minutes for them to load 100k lines.

However, if you want to relieve your cpu a bit and not hog all the main thread, you can split your data in chunks of x hundreds or x thousands lines, and load those chunks while waiting a bit between each.

(untested code)
```ts
async function wait(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function loadAll(data: string[]) {
  // Make chunks of 1000 items
  const chunks: string[][] = [];
  for (let i = 0; i < data.length; i += 1000) {
    chunks.push(data.slice(i, i + 1000));
  }

  for (const chunk of chunks) {
    await markov.loadData(chunk);
    await wait(10);
  }
}
```

Once loaded, you should also export the corpus to reimport it later: https://github.com/scambier/markov-strings#export-and-importdata

**Comment by scambier** [comment]
This fork might be more suited to your usage https://github.com/claabs/markov-strings-db

(I've never used it myself)
