### ISSUE TITLE
Error in Markov-Strings

### ISSUE THREAD

**Issue by silvestrinidev** [scambier/markov-strings#24]
![image](https://github.com/scambier/markov-strings/assets/86329735/99497a23-f104-45a2-b5ce-297c550689cf)

**Comment by scambier** [comment]
Can I see your code?

**Comment by silvestrinidev** [comment]
![image](https://github.com/scambier/markov-strings/assets/86329735/972e2a8a-629a-4935-a15a-35c384b2f674)

**Comment by scambier** [comment]
I was more interested to see how you import the `Markov` class. Did you do it like described in the [readme](https://github.com/scambier/markov-strings#usage)?

**Comment by silvestrinidev** [comment]
ye 
![image](https://github.com/scambier/markov-strings/assets/86329735/7b59edbf-4063-46f1-b90f-1ca079a64586)

**Comment by scambier** [comment]
Could it be a problem with a bundler or something else? I don't really use .js files, only .ts, and this works as expected.

Maybe this will fix it
```js
import Markov from 'markov-strings'

const markov = new Markov.default()
console.log(markov)
```

**Comment by silvestrinidev** [comment]
same mistake, markov is not a constructor

**Comment by scambier** [comment]
What do you get when you `console.log(Markov)`?

**Comment by scambier** [comment]
Could not reproduce.
