### ISSUE TITLE
A question about refs and the input data.

### ISSUE THREAD

**Issue by johnhult** [scambier/markov-strings#5]
Hi, I really like the idea of this but I have a question.

So basically, I fed a shitload of Trump tweets into the data. ~3200 tweets as an array of strings were each string was it's own tweet. Then I used the buildCorpusSync and then I created a result.

What bothers me is that the result only have 2 refs (which seems kinda unlikely from ~3200 tweets) and I literally got a result that was a tweet he actually wrote. So it seems there's either something I'm missing or something is wrong in the calculation somewhere.

Here's my code. Feel free to see if I did something wrong.

`
        setupMarkov = async data => {
		this.markov = new Markov(data);
		await this.markov.buildCorpusSync();
		this.generateTweet();
	};

	generateTweet = async () => {
		const options = {
			maxLength: 280,
			minWords: 10,

			stateSize: this.state.stateSize, //this.state.stateSize is 1
			filter: result => {
				return result.string.endsWith(".");
			}
		};
		const result = await this.markov.generateSentence(options);
		console.log(result);
		const decodedString = result.string.replace("&amp;", "&");

		this.setState({
			tweet: decodedString
		});
	};
`

Also I noticed that even if you use a new options object with stateSize: 1 (as in above example), the markov.startWords are still on a 2 word basis.

Also I noticed that for a dataset of ~3200 it only generates 185 start words, also seems a bit low?

Don't mean to be a critic or anything, I just want to make sure I'm getting the maximum value out of the package :)

**Comment by scambier** [comment]
Hello @johnhult, could you give me a link where I can download your data (or a sample of it?).

> Don't mean to be a critic or anything, I just want to make sure I'm getting the maximum value out of the package :)

No problem, there are certainly a few bugs here and there that I haven't caught :)

**Comment by johnhult** [comment]
Aight! I json-stringified the data and saved to a file which I'll add here.

[data-json-stringified.txt](https://github.com/scambier/markov-strings/files/2494669/data-json-stringified.txt)

So basically it's an ~3200 length array of strings as mentioned. You'd have to run JSON.parse on it before using it.

Lets see what we can find! 💃

**Comment by scambier** [comment]
Here's how to fix your problem:
```js
const options = {
    maxLength: 280,
    minWords: 10,

    stateSize: 1, // A stateSize of 2 is usually better though
    filter: result => {
        return result.string.endsWith(".")
    }
}
const markov = new Markov(data, options) // The options object is passed to the constructor

markov.buildCorpusSync()
const sentence = markov.generateSentenceSync()
console.log(sentence)
```
Some options _need_ to be passed to the constructor, because they're used in the `buildCorpus()` phase.

So it's not really a bug, but a design (and documentation) problem that I will address soon. I hope this solves your issue :)
